### ISSUE TITLE
Sliver bottom sheet doesn't allow sticky sliver magic

### ISSUE THREAD

**Issue by KamilSztandur** [woltapp/wolt_modal_sheet#11]
Providing `MultiSliver` widget to `WoltModalSheetPage` with `SliverPersistentHeaders` inside should allow them to stick their headers below bottomsheet top bar. Right now content scrolls behind top bar and sticks there where it's hidden because top bar overlaps it. Turning `isTopBarVisibleWhenScrolled` to `false` allows us to see it, but top bar is gone.

**How it should work:**

https://github.com/woltapp/wolt_modal_sheet/assets/61657553/d9039a49-a08e-42b5-8262-17e7a1850309

**How it actually works:**

https://github.com/woltapp/wolt_modal_sheet/assets/61657553/77079aab-0b79-4589-8a79-938d910844ca

**Comment by MbIXjkee** [comment]
The problem seems to be related to the fact that the composition in `WoltModalSheetLayout` uses Stack. The viewport of the main scrollable content is the whole space we have. `topBarAnimatedBuilder` as well as `sabAnimatedBuilder` don't affect this space at all and are painted over this space. It also affects the last element in the list (this element is hidden by `sabAnimatedBuilder` overpainting). I see two options to fix it: to find a workaround for detecting the current state of builders' sizes and reduce the space of content (some kind of emulation of these builders being in the scrollable area), or try to change the approach to layout in `WoltModalSheetLayout` and really to put them into a scrollable area (big changes). @ulusoyca what do you think about it?

**Comment by MoyinShabi** [comment]
Hi @KamilSztandur. Might using the new `isTopBarLayerAlwaysVisible` field present in this PR #31 help with this issue? According to your intended design, it seems like the top bar should always be visible.
