### ISSUE TITLE
playground need refactor

### ISSUE THREAD

**Issue by AcarFurkan** [woltapp/wolt_modal_sheet#143]
## Bug report

playground refactor 
refactor required and clean up deprecated codes for the playground example
for example:
<img width="567" alt="image" src="https://github.com/woltapp/wolt_modal_sheet/assets/65075121/178ecdad-51e4-4e34-94f2-a24191510d38">

<img width="563" alt="image" src="https://github.com/woltapp/wolt_modal_sheet/assets/65075121/128f77a4-5fa7-4889-b62c-2be856a10a1a">

**Comment by ulusoyca** [comment]
@AcarFurkan The min. supported Flutter version is 3.7.2 and this is not supported there. We follow the min. Flutter SDK update so that we support the version 1 year before the lastest stable release (This makes 4 stable Flutter release). This means that we will bump the min version Flutter 3.10.0 in the next Flutter stable version which is on May. 
https://github.com/woltapp/wolt_modal_sheet/blob/main/pubspec.yaml#L8
