### ISSUE TITLE
Refactor playgroundNavigator2 example

### ISSUE THREAD

**Issue by AcarFurkan** [woltapp/wolt_modal_sheet#145]
## Bug report
'location' is deprecated in playground navigator2 example and shouldn't be used. Use uri instead. This feature was deprecated after v3.8.0-3.0.pre.

<img width="640" alt="image" src="https://github.com/woltapp/wolt_modal_sheet/assets/65075121/12648dd6-5f08-48fb-897c-628608332b9f">

### Steps to reproduce

./playground_navigator2/lib/router/playground_route_information_parser.dart

**Comment by ulusoyca** [comment]
@AcarFurkan The min. supported Flutter version is 3.7.2 and this is not supported there. We follow the min. Flutter SDK update so that we support the version 1 year before the lastest stable release (This makes 4 stable Flutter release). This means that we will bump the min version Flutter 3.10.0 in the next Flutter stable version which is on May. 
https://github.com/woltapp/wolt_modal_sheet/blob/main/pubspec.yaml#L8
