### ISSUE TITLE
useSafeArea: only top/bottom

### ISSUE THREAD

**Issue by blingkonnerth** [woltapp/wolt_modal_sheet#277]
Currently we can set if the `bottomSheet` should respect the `SafeArea` entirely or not, via `useSafeArea`. 

Request:

Be able to set `SafeArea` **only** for `top` or `bottom`.

**Comment by ulusoyca** [comment]
@blingkonnerth Are you using the version 0.7.x? What you can do is to create your own bottom sheet type as in [ReadMe description](https://pub.dev/packages/wolt_modal_sheet#defining-custom-modal-types). Then you need to override the either modal decorator or modal content decorater as explained [here](https://pub.dev/packages/wolt_modal_sheet#modal-type-level-decoration).

By overriding these methods, you can provide your own safe area with own requirements. Please let me know if that helps so that I can close the issue.

**Comment by blingkonnerth** [comment]
Upgrading to **0.7.1** and creating a `CustomBottomSheetType`:

```
class UIBottomSheetDefaultType extends WoltBottomSheetType {
  const UIBottomSheetDefaultType() : super();

  @override
  Widget decorateModal(BuildContext context, Widget modal, bool useSafeArea) {
    return SafeArea(
      // SafeArea top should always be respected, so the time/battery is always visible.
      top: true,
      bottom: useSafeArea,
      right: useSafeArea,
      left: useSafeArea,
      child: modal,
    );
  }

  
}
```
